import { ProjectModel, ShotModel } from "@/types/shot";
import { generateStoryboardSvgUrl } from "@/lib/storyboardGraphics";

export function createDemoMatrixProject(): ProjectModel {
  const rawShots = [
    {
      id: "shot-matrix-1",
      sequence_id: "seq-matrix-1",
      order: 1,
      duration: 2.5,
      shot_size: "extreme_wide_shot" as const,
      camera_angle: "high_angle" as const,
      camera_movement: { type: "crane", speed: "slow" },
      subject: "古风茶楼与赛博雨夜",
      action: "俯瞰赛博雨夜，青瓦飞檐的古风茶楼悬挂着发光的红灯笼，周围环绕着绿色全息数据流与密集的雨幕。",
      composition: { subject_position: "center", depth_elements: ["roof_tiles", "hologram_signs"] },
      character_direction: "static" as const,
      narrative_function: "环境建立",
      lighting: "暗红霓虹与绿色数据流反光",
      audio: { ambient: "heavy_rain_and_thunder", music: "cyber_guzheng_intro" },
      transition: "cut",
      image_prompt: "Cinematic 2D storyboard sketch, extreme wide shot high angle, ancient Chinese cyberpunk tea house with red lanterns in heavy rain, green matrix code rain streaming in dark night sky.",
      video_prompt: "Camera cranes down through neon rain onto the ancient cyber tea house rooftops.",
      continuity_data: { screen_direction: "static" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-2",
      sequence_id: "seq-matrix-1",
      order: 2,
      duration: 2.0,
      shot_size: "wide_shot" as const,
      camera_angle: "eye_level" as const,
      camera_movement: { type: "tracking_right", speed: "medium" },
      subject: "墨客 (Moke)",
      action: "墨客身穿黑色立领长衫风衣，戴着黑色墨镜，缓步踏过水洼，皮靴带起一圈圈慢动作水花涟漪。",
      composition: { subject_position: "frame_left", focal_point: "center" },
      character_direction: "left_to_right" as const,
      narrative_function: "主角登场",
      lighting: "侧逆光勾勒修长风衣轮廓",
      audio: { sfx: ["footsteps_splashing_water"] },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, wide shot eye level, kung fu master in black modern changshan trenchcoat and sunglasses walking through rain puddles in neon alley.",
      video_prompt: "Tracking camera moves alongside the master walking in slow motion through rain.",
      continuity_data: { screen_direction: "left_to_right" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-3",
      sequence_id: "seq-matrix-1",
      order: 3,
      duration: 2.0,
      shot_size: "medium_shot" as const,
      camera_angle: "low_angle" as const,
      camera_movement: { type: "push_in", speed: "medium" },
      subject: "特工银狐 (Agent Fox)",
      action: "特工银狐从茶馆暗影中缓步走出，右手微抬，袖口机械装置发出淡蓝色充能微光。",
      composition: { subject_position: "frame_right" },
      character_direction: "right_to_left" as const,
      narrative_function: "反派现身",
      lighting: "机械冷蓝光照射面部",
      audio: { sfx: ["cyber_servo_hum", "energy_charging"] },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, medium shot low angle, cyber agent in sleek black suit stepping out of shadows with glowing cybernetic blade on wrist.",
      video_prompt: "Slow push in on the cyber agent activating arm blade with menacing grin.",
      continuity_data: { screen_direction: "right_to_left" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-4",
      sequence_id: "seq-matrix-1",
      order: 4,
      duration: 2.5,
      shot_size: "medium_close_up" as const,
      camera_angle: "eye_level" as const,
      camera_movement: { type: "static" },
      subject: "墨客 (Moke)",
      action: "墨客面容沉静，双手从容展开摆出经典咏春/太极问手起手式，手指轻勾：“请。”",
      dialogue: "“请。”",
      composition: { subject_position: "center" },
      character_direction: "left_to_right" as const,
      narrative_function: "宗师起势",
      lighting: "正面柔和雨光泛白",
      audio: { music: "bamboo_flute_tense" },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, medium close up, Chinese kung fu master raising hands into Wing Chun open stance, rain droplets freezing around fingertips.",
      video_prompt: "Static shot, master smoothly raises hands into iconic martial arts guard, taunting finger gesture.",
      continuity_data: { screen_direction: "left_to_right" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-5",
      sequence_id: "seq-matrix-1",
      order: 5,
      duration: 2.0,
      shot_size: "full_shot" as const,
      camera_angle: "dutch_angle" as const,
      camera_movement: { type: "handheld", speed: "fast" },
      subject: "特工与墨客",
      action: "特工暴喝一声率先发难，瞬步暴冲撕裂雨雾，重拳带起空气激波直轰墨客面门。",
      composition: { subject_position: "center_action" },
      character_direction: "right_to_left" as const,
      narrative_function: "战斗爆发",
      lighting: "雨夜雷电骤闪强光",
      audio: { sfx: ["explosive_dash", "air_whoosh"] },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, full shot dutch angle, cyber agent lunging forward with supersonic speed shattering rainwater in martial arts attack.",
      video_prompt: "Fast handheld camera captures explosive sprint and heavy fist strike.",
      continuity_data: { screen_direction: "right_to_left" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-6",
      sequence_id: "seq-matrix-1",
      order: 6,
      duration: 3.0,
      shot_size: "close_up" as const,
      camera_angle: "low_angle" as const,
      camera_movement: { type: "tracking_left", speed: "fast" },
      subject: "拳脚拆招",
      action: "墨客不退反进，左右黐手黏带化劲，手腕翻转顺势格挡，两人近身拳影交错火花四溅。",
      composition: { subject_position: "center" },
      character_direction: "left_to_right" as const,
      narrative_function: "近身拆招",
      lighting: "格挡撞击火花四射",
      audio: { sfx: ["rapid_parry_impacts", "metal_sparks"] },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, close up low angle, intricate Wing Chun sticky hands parrying cybernetic fist, electric sparks and rain flying.",
      video_prompt: "High-speed camera tracks lightning-fast Chinese martial arts blocking and deflection.",
      continuity_data: { screen_direction: "left_to_right" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-7",
      sequence_id: "seq-matrix-1",
      order: 7,
      duration: 3.5,
      shot_size: "extreme_close_up" as const,
      camera_angle: "eye_level" as const,
      camera_movement: { type: "pan_left", speed: "sudden" },
      subject: "电磁枪拔枪",
      action: "特工近战受阻，左手突然拔出高科技电磁手枪直抵墨客眉心，决然扣动扳机。",
      composition: { subject_position: "center" },
      character_direction: "right_to_left" as const,
      narrative_function: "危机升级",
      lighting: "枪口蓝色电浆聚能闪耀",
      audio: { sfx: ["gun_draw_click", "plasma_energy_charge"] },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, extreme close up, agent drawing futuristic electromagnetic pistol directly aimed at protagonist's forehead.",
      video_prompt: "Snap pan to the pistol muzzle charging with blue plasma spark.",
      continuity_data: { screen_direction: "right_to_left" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-8",
      sequence_id: "seq-matrix-1",
      order: 8,
      duration: 3.5,
      shot_size: "medium_shot" as const,
      camera_angle: "worms_eye" as const,
      camera_movement: { type: "tracking_right", speed: "slow" },
      subject: "墨客子弹时间铁板桥",
      action: "【经典子弹时间】镜头360度极慢速环绕，墨客极限铁板桥下腰，电磁子弹旋转穿透悬浮水珠，在墨镜上方划出清晰气浪。",
      composition: { subject_position: "center_horizontal" },
      character_direction: "left_to_right" as const,
      narrative_function: "高潮视效 (Bullet Time)",
      lighting: "等离子子弹金色尾迹与数据流光",
      audio: { sfx: ["bullet_time_slowdown", "deep_air_distortion"] },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, medium shot worms eye angle, iconic Matrix Bullet Time dodge, kung fu master bending backwards horizontally dodging spiraling glowing bullet through frozen rain drops.",
      video_prompt: "Iconic 360-degree matrix bullet-time camera spin around master bending back as bullet leaves vapor trail.",
      continuity_data: { screen_direction: "left_to_right" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-9",
      sequence_id: "seq-matrix-1",
      order: 9,
      duration: 2.5,
      shot_size: "medium_close_up" as const,
      camera_angle: "low_angle" as const,
      camera_movement: { type: "push_in", speed: "medium" },
      subject: "墨客起身特写",
      action: "墨客腰背借力如春藤回弹起身，墨镜上赫然反光映出特工惊恐瞪大的双眼。",
      composition: { subject_position: "center" },
      character_direction: "left_to_right" as const,
      narrative_function: "攻守逆转",
      lighting: "墨镜镜片反光高亮",
      audio: { music: "epic_crescendo_drop" },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, medium close up low angle, protagonist springing back up effortlessly, agent's shocked expression reflected on black sunglasses.",
      video_prompt: "Rapid push-in as master recovers balance with spring-loaded martial arts momentum.",
      continuity_data: { screen_direction: "left_to_right" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-10",
      sequence_id: "seq-matrix-1",
      order: 10,
      duration: 2.5,
      shot_size: "full_shot" as const,
      camera_angle: "dutch_angle" as const,
      camera_movement: { type: "tracking_right", speed: "fast" },
      subject: "凌空飞踢",
      action: "墨客借势腾空而起，在空中展开华丽的凌空飞踢（三连佛山无影脚），重重踏在特工胸膛护甲上。",
      composition: { subject_position: "center" },
      character_direction: "left_to_right" as const,
      narrative_function: "终结打击",
      lighting: "气劲爆发青白色冲击波",
      audio: { sfx: ["heavy_impact_strike", "energy_shockwave"] },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, full shot dutch angle, kung fu master executing mid-air flying kick into the cyber agent's chest, shockwave dispersing rain.",
      video_prompt: "Fast tracking shot follows soaring flying kick landing squarely on enemy armor.",
      continuity_data: { screen_direction: "left_to_right" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-11",
      sequence_id: "seq-matrix-1",
      order: 11,
      duration: 2.0,
      shot_size: "wide_shot" as const,
      camera_angle: "high_angle" as const,
      camera_movement: { type: "pull_out", speed: "fast" },
      subject: "特工倒飞坠地",
      action: "特工如炮弹般倒飞撞穿茶馆二楼的雕花木格屏风，木屑与雨瓦轰然炸裂，狠狠摔入街巷积水中。",
      composition: { subject_position: "center" },
      character_direction: "left_to_right" as const,
      narrative_function: "胜负已分",
      lighting: "茶楼内部暖黄灯光从破洞倾泻",
      audio: { sfx: ["wood_lattice_shattering", "heavy_water_splash"] },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, wide shot high angle, agent crashing through ornate wooden Chinese lattice screen window, wood splinters and roof tiles exploding into alley.",
      video_prompt: "Camera pulls back rapidly as enemy crashes through traditional lattice wood screen.",
      continuity_data: { screen_direction: "left_to_right" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "shot-matrix-12",
      sequence_id: "seq-matrix-1",
      order: 12,
      duration: 2.0,
      shot_size: "medium_shot" as const,
      camera_angle: "eye_level" as const,
      camera_movement: { type: "static" },
      subject: "墨客收势",
      action: "墨客潇洒单膝落地后挺拔站起，单手轻拂长衫下摆，四周雨水流速瞬间恢复正常，从容收势。",
      composition: { subject_position: "center" },
      character_direction: "static" as const,
      narrative_function: "宗师收式 (Ending)",
      lighting: "冷峻月光从瓦檐倾泻，水雾缭绕",
      audio: { music: "calm_cyber_flute_outro", ambient: "gentle_dripping_rain" },
      transition: "cut",
      image_prompt: "Cinematic storyboard sketch, medium shot eye level, kung fu master standing poised in the rain dusting off his black coat, tranquil and victorious.",
      video_prompt: "Static ending frame as rain returns to normal speed, master quietly exhales and straightens coat.",
      continuity_data: { screen_direction: "static" },
      is_dirty: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  const populatedShots: ShotModel[] = rawShots.map((s) => ({
    ...s,
    camera_movement: {
      ...s.camera_movement,
      speed: s.camera_movement.speed as 'slow' | 'medium' | 'fast' | 'sudden' | undefined,
    },
    storyboard_image_url: generateStoryboardSvgUrl({
      order: s.order,
      shot_size: s.shot_size,
      camera_angle: s.camera_angle,
      action: s.action,
      subject: s.subject,
    }),
  })) as ShotModel[];

  return {
    id: "demo-matrix-cyber-master",
    user_id: "demo-user",
    title: "矩阵·赛博宗师：雨夜茶馆决战",
    story: "赛博雨夜，青瓦飞檐的古典中式茶楼隐没在全息霓虹广告与绿色数据流雨幕中。黑客武术大师墨客身着黑色立领长衫风衣踏入雨巷，与拦截的特工银狐狭路相逢。两人展开惊心动魄的近身功夫对决，经历了电磁枪拔枪、经典360度子弹时间铁板桥闪避、凌空三连踢，最终特工被踢飞撞碎雕花屏风，墨客收势伫立在雨中。",
    target_duration: 30.0,
    style_config: {
      visual_style: "Cinematic 2D animation storyboard sketch style, green Matrix rain and neon amber highlights, Kung Fu action"
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    sequences: [
      {
        id: "seq-matrix-1",
        project_id: "demo-matrix-cyber-master",
        order: 1,
        name: "雨夜茶馆决战 (Showdown in Neon Rain)",
        shots: populatedShots,
      },
    ],
  };
}
